---
- name: install dokku
  shell: |
    creates=/usr/local/bin/dokku
    wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | sudo bash

- template: src=VHOST.j2 dest=/home/dokku/VHOST owner=root group=root mode=0644

- stat: path=/home/dokku/.ssh/authorized_keys
  register: authorized_keys
- name: sshcommand acl-add dokku
  shell: |
    FIRSTUSER=$(getent passwd 1000 | cut -d: -f1)
    cat /home/$FIRSTUSER/.ssh/authorized_keys | sudo sshcommand acl-add dokku vagrant
  when: authorized_keys.stat.size == 0

- lineinfile: dest="/etc/ssh/sshd_config" regexp="^AllowUsers dokku" line="AllowUsers dokku"
  notify:
  - restart ssh
  - etckeeper commit

- lineinfile: dest="/etc/default/grub" regexp='^GRUB_CMDLINE_LINUX=' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  notify:
  - update-grub
  - etckeeper commit
